import pyautogui
import time

pyautogui.hotkey("win")
pyautogui.write("Google Chrome")
pyautogui.hotkey("enter")
time.sleep(1.5)
pyautogui.hotkey("clear")
pyautogui.write("https://favelaware.animahub.com.br/cronograma-2")
pyautogui.hotkey("enter")
time.sleep(2)
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.hotkey("tab")
pyautogui.hotkey("tab")
pyautogui.hotkey("enter") 